// <auto-generated />
namespace MovieTickets.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class audFix2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(audFix2));
        
        string IMigrationMetadata.Id
        {
            get { return "202204231433099_audFix2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
