// <auto-generated />
namespace MovieTickets.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MultipleFixesOnMovies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MultipleFixesOnMovies));
        
        string IMigrationMetadata.Id
        {
            get { return "202202160013219_MultipleFixesOnMovies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
